### ISSUE TITLE
Photographs

### ISSUE THREAD

**Issue by danigocrypto** [honest-cash/honestcash#2]
Hi,
I don't know if it is because of browser compatibility or if it is a deeper fix, but it is not possible to add a photograph to your profile at this time. not a big deal but i'm guessing you want it working eventually.
laters... 

ps. it would be awesome to be able to add photographs to the actual articles...

**Comment by adrianbarwicki** [comment]
Thanks a lot for submitting the issue. We have just found out what the problem was and corrected it.

Check out a short demo here:
https://www.useloom.com/share/27c32403f94643538b3205faf93ab8c0

We have put the feature of adding photos to articles to our roadmap and we are implementing it as soon as possible.

**Comment by adrianbarwicki** [comment]
Can you provide what browser and device did you test on so we double-check that it also works in your env.?

**Comment by adrianbarwicki** [comment]
Fixed.
